### ISSUE TITLE
henvcfg.HADE vs mstatus.TVM

### ISSUE THREAD

**Issue by sorear** [riscv/riscv-svadu#11]
If mstatus.TVM=1, then the translation structures pointed to by satp and hgatp are logically owned by M-mode code (or a different HS-mode context, but definitely not this HS-mode context). If M-mode wishes to expose "menvcfg.HADE=1" semantics to the HS-mode context (for instance in order to support a future profile), the HS-mode context must be able to write henvcfg.HADE and read back the value it wrote. Doing so, the HS-mode context changes the behavior of translation structures it does not own.

I don't think this is a problem with the spec in its current version, since shadow page tables can easily be constrained by software to work regardless of henvcfg.HADE, but the requirement should be clearly documented to avoid future problems.  Alternatively, henvcfg.HADE could be ignored by hardware if mstatus.TVM=1 (with a similar requirement on (v)senvcfg.HADE if mstatus.TVM || hstatus.VTVM && V, if such a thing were added).

There is no problem associated with HS-mode's view of its own page tables, since the software page table walk that occurs on a shadow page table miss can inspect the hardware-ignored HADE bits and act on them.

**Comment by ved-rivos** [comment]
henvcfg cannot be written at VS privilege. Access to henvcfg when V=1 should lead to a virtual instruction exception. The henvcfg establishes the environment for VS mode execution and is not expected to be written by VS mode.

**Comment by sorear** [comment]
Mixed up the abbreviations.  Fixed.

**Comment by ved-rivos** [comment]
henvcfg does not affect execution in HS mode. If M mode intends to be the execution environment for VS - instead of HS as in this example - is in addition to using TVM it would be required to use TSR to intercept SRET as there are other control fields  that affect VS mode data structures - including page tables - such as the endianness controlled by hstatus.VSBE, VS mode virtual memory schemes that can be selected in vsatp as controlled by hstatus.VSXL, page based memory types controlled by henvcfg.PBMTE, etc. Since the necessary hooks to perform such emulation, more architecture around this does not seem to be required.

**Comment by sorear** [comment]
My mistake was thinking henvcfg.HADE affected the interpretation of hgatp.  Since it's actually controlling vsatp, this is a false alarm.
