### ISSUE TITLE
The non-normative text needs to be clearly demarcated from the normative text.

### ISSUE THREAD

**Issue by kdockser** [riscv/riscv-svadu#16]
The spec starts off with an explanation of how the A/D bits are updated by hardware. However, this feature has already been detailed and ratified in the Privileged Specification - which also talks about the option of taking a page-fault exception instead of updating these bits in hardware. This initial text reiterates that definition with some textual changes. Presumably, it is not intended to change the behavior of hardware updates of the A/D bits. To avoid confusion, this should be clearly marked as being non-normative text.

It seems that the intention here is to say that if the Svadu is implemented then the PTE A and D bits are updated by hardware. If so, it seems that this could be stated in a more concise and consistent fashion. For example: 
`The Svadu extension requires that the PTE A and D bits are managed using the hardware scheme as defined in the Privileged Architecture Specification.`

The other ISA changes in the specification are clear and concise:

1. the requirement that the page tables be located in memory with hardware page-table write
access and RsrvEventual PMA.
2. the addition of the ADUE bit to the menvcfg/henvcfg CSRs

**Comment by ved-rivos** [comment]
This is intentional. This extension provides all the normative specification for H/W updating of PTE A/D bits. The Svade extension on other hand causes a page-fault when A and/or D bits are clear when required to be 1. As you rightly noted the Priv spec has had had the H/W updating behavior but was not complete as it did not include the controls for enabling the H/W updating.

**Comment by gfavor** [comment]
Also note that when Svadu was reviewed, it was decided that it would be
appropriate to modify the existing Priv text so that that text and the
Svadu extension text would better and more clearly co-exist.  This
modification to the existing Priv text will be part of the various
clarifications and changes that comprise Priv 1.13 (which is starting to be
put together for review now that the Priv conversion to adoc has been
completed).

Greg

**Comment by kdockser** [comment]
OK, that makes sense. I wasn't aware that the corresponding section of the Priv Spec was going to be updated so that these two could co-exist. Without such a change, this spec would have been redefining a behavior - something we work hard to avoid.
