### ISSUE TITLE
PTE-Update text can be misleading

### ISSUE THREAD

**Issue by kdockser** [riscv/riscv-svadu#20]
In the _Hardware Updating of PTE A/D Bits_ section of the document, the description of what must be done atomically needs to be disambiguated.

`The PTE update must be atomic with respect to other accesses to the PTE, and must atomically check that the PTE is valid and grants sufficient permissions as part of conditionally making the update.`

The use of the word "valid" could be read as referring the PTE "V" bit (I assume that it meant to allude to the use of the word "valid" in step 2 In 5.3.2 _Virtual Address Translation Process_ of the Privileged specification). Thus, a reader may think that this is saying that only the PTE U, X, W, R,  and V bits must be checked atomically - but other changes are OK.

I suggest that this wording be changed to be closer to 4: 

`The PTE update must be atomic with respect to other accesses to the PTE, and must atomically check that the PTE has not changed since it was last checked as part of the page table walk`

**Comment by ved-rivos** [comment]
> Thus, a reader may think that this is saying that only the PTE U, X, W, R, and V bits must be checked atomically - but other changes are OK.

The text is right. As long as the update ensures that the PTE is valid - `v=1` and does not have any reserved encodings - and grants sufficient permissions the A and/or D bit update can be done.

**Comment by kdockser** [comment]
This differs from step 7 in `5.3.2 Virtual Address Translation Process` which states that the entire PTE needs to be compared with what had previously been checked.  

```
Perform the following steps atomically:

- Compare pte to the value of the PTE at address a + va.vpn[i] × PTESIZE.
- If the values match, set pte.a to 1 and, if the original memory access is a store, also set pte.d to 1.
- If the comparison fails, return to step 2

```

Which one of these is wrong, the text in Svadu or this text in the Privileged spec?

**Comment by ved-rivos** [comment]
Both of these texts are from the Priv specification:
This text from the [Priv specification](https://github.com/riscv/riscv-isa-manual/blob/main/src/supervisor.adoc?plain=1#L1220 ) textually says what the suggested process does in [step 7](https://github.com/riscv/riscv-isa-manual/blob/main/src/supervisor.adoc?plain=1#L1306) of the Priv specfication does to achieve that property.

**Comment by kdockser** [comment]
Yes, they are both from the privileged spec but one is moving to the Svadu spec - so I thought this would be a good time to fix it.

They do not just differ in that one is property and the other is procedure; they differ in meaning. One requires that a few bits of the PTE are the same, while the other requires that the whole PTE remains the same - the later is more consistent with other architectures.

**Comment by ved-rivos** [comment]
Both pieces of the text are moving into the Svadu spec but that is only for document organization purposes. The Svadu spec is not changing the privilege architecture. Svadu extends it by adding a control to enable/disable the H/W updating of A/D bits. I am not sure there is a contradiction between the two. It would be good if this issue was moved to the Priv. ISA manual.

**Comment by ved-rivos** [comment]
Resolving this issue as the text in section 5.3.1 provides the conditions to enforce for performing an A/D update and section 5.3.2 provides the precise recipe for performing the A/D update to avoid any misinterpretations.

**Comment by kdockser** [comment]
The Hardware Updating of PTE A/D Bits section provides specific requirements for updating the A/D bits which differer from the stricter specific requirements given elsewhere in this spec. This gives the specification ambiguity as there are two choices on how to implement the check for Updating A/D.

The minor change that I proposed above would eliminate this ambiguity by actually making the "Updating" requirements an abstraction which would require the implenter to look for the actual details provided elsewhere in the SVADU spec.

@aswaterman @greg Ved was thinking this is a privileged arch issue, but I believe it is an svadu issue as that is where it is being moved to.

**Comment by ved-rivos** [comment]
>Ved was thinking this is a privileged arch issue,

@kdockser I don't think its an issue. This text in section 5.3.1states the property to achieve and the process outlined in section 5.3.2 provides the precise steps to do that.

**Comment by gfavor** [comment]
Maybe I'm missing something, but looking at the latest release ...

The Svadu "step 7" text matches what is in the current Priv spec's "step 7" text in saying:

> Perform the following steps atomically:
i. Compare pte to the value of the PTE at address a + va.vpn[i] × PTESIZE.
ii. If the values match, ...

Maybe an earlier version of Svadu spec'ed just checking that the PTE is valid and grants sufficient permissions, but the current spec release checks for the entire PTE to be the same.

**Comment by ved-rivos** [comment]
In section 5.3.1, there is a textual specification of the properties to enforce for doing A/D update. The properties outlined there state "and must atomically check that the PTE is valid and grants sufficient permissions". Then the section 5.3.2 of the priv spec provides the precise steps to achieve this - the step 7. Both these pieces were moved into the Svadu specification. The text that Ken feels is misleading is the text I quoted above from section 5.3.1.

**Comment by gfavor** [comment]
Thanks.  Now I understand the concern by Ken.

This does seem like a good opportunity to clarify the section 5.3.1 text (now moving into Svadu) to avoid any seeming discrepancy to some readers (since a literal read would show a discrepancy).  We shouldn't expect readers to have to read both chunks of text and conclude that the first text was just a more conceptual statement and one shouldn't get picky about it not exactly matching the "step 7" text.  Especially if there is a simple fix.

Maybe tweaking (without totally changing) the text to say:    "and must atomically check that the PTE is valid, grants sufficient permissions, and does not require any exception to be raised."

This added text fully covers steps 2-6 that are intended to be part of the atomic PTE update.

@aswaterman should review my suggestion and see if he agrees with it or not.

Btw (Andrew), doesn't some modified version of the section 5.3.1 text for hardware updating of A&D bits (now moving into Svadu), need to be kept in the Priv spec as part of the "take a page fault" scheme?  Not as a statement that matters to hardware, but a statement as to how software must go about atomically setting A&D bits.  Especially since the existing step 7 will go away and hence that pseudocode will no longer convey the full extent of the atomic update requirement that software must implement.

**Comment by kdockser** [comment]
Thanks,  Greg. I think my original proposal also achieves the goal of not totally changing the text:

`The PTE update must be atomic with respect to other accesses to the PTE, and must atomically check that the PTE has not changed since it was last checked as part of the page table walk`

My point is _all_ bits of the PTE must remain unchanged. This was not a comment about potential expceptions, but rather about avoiding the updating of A/D bits when the PTE remained valid but the PPN had changed, for example.

**Comment by ved-rivos** [comment]
I feel that statement is misleading since it may imply that A/D update is not done if the PTE has changed. The PTE update process retries the compare-and-exchange if the PTE has change. I suggest updating as follows:

> The PTE update must be atomic with respect to other accesses to the PTE and must atomically check that the PTE is valid and grants sufficient permissions, **all as part of conditionally making the update in accordance with Step 7 of the process specified by this specification**.

**Comment by gfavor** [comment]
I sort of agree.  But the "since it was last checked" might be misread by some readers (since this is being stated separate from the actual tablewalk pseucode).  Some might read that to mean that the PTE doesn't need to be re-read and re-checked atomically as part of doing the atomic A&D update.

To avoid misreading, it would have to be something like:

> The PTE update must be atomic with respect to other accesses to the PTE, and must atomically perform all tablewalk checks as part of and before updating that PTE value.

**Comment by gfavor** [comment]
Ved, would you agree that my latest suggestion is equivalent to yours and is safely (wrt misreading) more concise?

Although, for that matter, your text doesn't make clear that all the other PTE checks must also be performed as part of this overall atomic update (and is leaning on the pseudocode to correct what a literal reading of your text appears to say).

**Comment by ved-rivos** [comment]
Yea our posts raced but your proposal is equivalent and concise.

**Comment by kdockser** [comment]
I think we are getting much closer.  I'm concerned that this latest proposal might be read as all of the table walk must occur atomically - where it is only the recheck and update that must be atomic.

How about something along these lines:

`The PTE update must be atomic with respect to other PTE accesses and must be performed atomically with a  successful compare of the PTE. An unsuccessful compare results in restarting the page table walk.`

**Comment by gfavor** [comment]
Good point.  Although, to stay away from an implementation-oriented description (albeit based on a very reasonable approach) and staying more architectural, a few extra words would result in:

> The PTE update must be atomic with respect to other accesses to the PTE, and must atomically perform all the tablewalk checks for that leaf PTE as part of and before updating that PTE value.

**Comment by ved-rivos** [comment]
@gfavor @kdockser - Please review PR #23 .

**Comment by kdockser** [comment]
Greg, I agree that the architectural approach is better. Ved, the PR looks good to me.
Thanks!
Ken

**Comment by ved-rivos** [comment]
Thanks @kdockser @gfavor
