### ISSUE TITLE
"a trap may occur between the PTE update and the memory access"?

### ISSUE THREAD

**Issue by ingallsj** [riscv/riscv-svadu#3]
The ISA spec says

> updates to the D bit must be exact (i.e., not speculative)

and the proposed extension spec says

> a trap may occur between the PTE update and the memory access that caused the PTE update.

This is a new relaxation from the base Privileged ISA spec.

1. What scenario prompted us to add it?
- I presume something to do with the D bit, since the A bit can be updated speculatively.
- Was it something to do with page-crossing misaligned or multi-element vector accesses?

2. Can we please be more specific: _which_ traps are allowed here?
- Looking at Table 3.7 "Synchronous exception priority in decreasing priority order", there is a spectrum of possibilities.
- Other ISAs spend pages painfully elaborating the exact fault checking sequence, and listing out allowable behaviors.

In my vocabulary, an instruction that is non-speculative is right up at the line between being able to trap and not, and this sentence gives.

**Comment by ved-rivos** [comment]
So this is not new text. The privileged specification presently states "The PTE update is not required to be atomic with respect to the explicit memory access that caused the update, and the sequence is interruptible." The "sequence is interruptible" was clarified to indicate "a trap may occur between the PTE update and the memory access that caused the PTE update". It is not related specifically to D bits. Some examples - 1) When two-stage address translation is, A bits may get set in the g-stage PTEs for each vs-stage PTE  access but there may be a trap - an access fault or a page  fault or a guest page fault or any of the other traps defined to occur as part of the virtual address translation process - that may occur. 2) When the leaf VS-stage PTE is determined, the A and/or D bits may be set in the VS-stage PTE but a trap occur due to the G-stage walk to translate the GPA to an SPA. 3) After the virtual address was translated successfully a trap may occur due to the memory access itself for example - an abort signaled by the  memory, access to corrupted data (e.g., poisoned data), timeout waiting for the target to provide data, violation of a PMA or PMP rule, etc.

**Comment by ingallsj** [comment]
Yes, I agree with all those scenarios.  Other ISAs spend pages painstakingly elaborating them, but let's not do that here.  For now, a smidgeon of clarification could help the reader along: **bolded text**

"If a trap occurs **later in the translation process** then the A and/or D bit may be updated but the memory access that caused the PTE update may not occur.

**Comment by pdonahue-ventana** [comment]
If a change is to be made to that sentence, can we avoid the term "may not" since that could be construed in different ways?  I suggest either "might not" or "must not" as appropriate.

**Comment by ved-rivos** [comment]
So the trap may occur later but  not necessarily in the translation process. For example due to PMA checks:

**Comment by ved-rivos** [comment]
PR #7 to address this issue.
